#!/bin/bash

set -e -u

source $(dirname $0)/common.sh

git checkout $merged_branch

progress "rewriting all imports"
ag --go -l github.com/dexidp/dex | xargs sed -i -e 's|"github.com/dexidp/dex|"github.com/concourse/dex|g'

progress "rewriting module name"
sed -i -e 's|module github.com/dexidp/dex|module github.com/concourse/dex|g' go.mod

git commit -a -m "rewrite imports to concourse fork"

progress "tagging so that the ref is preserved after the next force-push"
tag_name=merged-$(date "+%Y%m%d%H%M%S")
git tag $tag_name
git push origin $tag_name

progress "done!"

echo "$tag_name" > "tag_name"