#!/bin/bash

set -e -x

set -o pipefail

git fetch origin
git fetch upstream master

function rebase_target() {
  case $1 in
  pr/add-name-claim)
    echo upstream/master
    ;;
  pr/add-cf-connector)
    echo pr/add-name-claim
    ;;
  pr/add-oauth-connector)
    echo pr/add-name-claim
    ;;
  pr/add-web-host-url)
    echo pr/password-grant
    ;;
  pr/password-grant)
    echo upstream/master
    ;;
  pr/github-teams-no-org-and-slugs)
    echo upstream/master
    ;;
  pr/gitlab-broken-auth-headers)
    echo upstream/master
    ;;
  pr/gitlab-include-user-scope-*)
    echo upstream/master
    ;;
  pr/oidc-groups-and-tls)
    echo pr/add-name-claim
    ;;
  pr/optional-prometheus-logger)
    echo upstream/master
    ;;
  pr/postgres-unix-sockets)
    echo upstream/master
    ;;
  pr/unset-pg-serializable-transaction-level)
    echo upstream/master
    ;;
  pr/remove-mysql-cockroachdb-drivers)
    echo upstream/master
    ;;
  *)
    ;;
  esac
}

git branch | tr '*' ' ' | grep pr/ | while read b _; do
  git checkout $b
  target=$(rebase_target $b)
  if [ -z "$target" ]; then
    echo "unknown rebase target for $b"
    exit 1
  fi

  rebase_target $b | xargs git rebase
done

git co maintenance
