#!/bin/bash

set -e -x

set -o pipefail

source $(dirname $0)/common.sh

git fetch origin
git fetch upstream master

$(dirname $0)/list-pr-branches | while read b _; do
  git checkout $b
  git rebase upstream/master $b
done

git checkout maintenance
