#!/bin/bash

set -e -u

source $(dirname $0)/common.sh

progress "fetching origin to sync pr branches"
git fetch origin
git remote update origin --prune

progress "fetching upstream master"
git fetch upstream master

progress "merging all PRs on fresh upstream"
git checkout $merged_branch
git reset --hard upstream/master
git branch -r | grep pr/ | sed -e 's|\s*origin/||' | xargs git merge

git checkout maintenance
./post-merge
