#!/bin/bash

set -e -u

pushd dex
source ci/scripts/common.sh

progress "fetching origin to sync pr branches"
git fetch origin
git remote update origin --prune

progress "fetching upstream release"
upstream_release_tag=v$(cat ../dex-github-release/version)
create-branch-track-upstream-release $upstream_release_tag

progress "merging all PRs on fresh upstream"
git checkout -b master
git reset --hard $upstream_release_tag
list-pr-branches | while read b _; do
  git merge "origin/$b"
done

progress "rewriting all imports"
grep -r -l --include="*.go" "github.com/dexidp/dex" . | xargs sed -i -e 's|"github.com/dexidp/dex|"github.com/concourse/dex|g'

progress "rewriting module name"
grep -r -l --include="*.mod" "github.com/dexidp/dex" . | xargs sed -i -e 's|github.com/dexidp/dex|github.com/concourse/dex|g'

# change api/v2 reference back to upstream
progress "rewriting module name"
grep -r -l '--include=*.'{go,mod} "github.com/concourse/dex/api/v2" . | xargs sed -i -e 's|github.com/concourse/dex/api/v2|github.com/dexidp/dex/api/v2|g'

# making sure all tests are passed
make testall

cat > ./release-note <<EOF
upstream dex release: $upstream_release_tag

$(cat ../dex-github-release/body)
EOF

git commit -a -F "./release-note"

progress "tagging so that the ref is preserved after the next force-push"
version=v$(cat ../concourse-dex-version/version)
git tag $version

git push origin $version

# override outdated master
git push origin HEAD -f
popd
