#!/bin/bash

set -e -u

pushd concourse-dex
source ci/scripts/common.sh

progress "fetching origin to sync pr branches"
git fetch origin
git remote update origin --prune

progress "fetching upstream master"
git fetch upstream master

progress "merging all PRs on fresh upstream"
git checkout $merged_branch
git reset --hard upstream/master
git branch -r | grep pr/ | sed -e 's|\s*origin/||' | xargs git merge

# making sure all tests are passed
make testall

progress "rewriting all imports"
grep -r -l --include="*.go" "github.com/dexidp/dex" . | xargs sed -i -e 's|"github.com/dexidp/dex|"github.com/concourse/dex|g'

progress "rewriting module name"
sed -i -e 's|module github.com/dexidp/dex|module github.com/concourse/dex|g' go.mod

git commit -a -m "rewrite imports to concourse fork"

progress "tagging so that the ref is preserved after the next force-push"
tag_name=merged-$(date "+%Y%m%d%H%M%S")
git tag $tag_name


# git push origin $tag_name

# progress "done!"
#popd

#echo "$tag_name" > concourse-dex-tag/tag_name

