#!/bin/bash

set -e -x

set -o pipefail

cd concourse-dex

source ci/scripts/common.sh

git fetch origin
git fetch upstream master

list-pr-branches | while read b _; do
  git checkout $b
  git rebase upstream/master
  git push -f origin $b:$b;
done
