#!/bin/bash

set -e -x

set -o pipefail

cd concourse-dex/ci/scripts

source common.sh

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git fetch origin
git fetch upstream master

./list-pr-branches | while read b _; do
  git checkout $b
  git rebase upstream/master $b
  git push -f origin $b:$b;
done
