#!/bin/bash

set -e -x

set -o pipefail

cd concourse-dex/ci/scripts

source common.sh

pushd concourse

apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
apt-add-repository https://cli.github.com/packages
apt update
apt install gh

cat concourse-dex-tag/tag-name
gh pr status

